services:
  client:
    build:
      context: ./client
    container_name: csv_client_dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - client-node-modules:/app/node_modules

volumes:
  client-node-modules:
